model_class: trading.models.orpheus.orpheus5classifier.Orpheus5Classifier
d_model: 64
nhead: 1
max_seq_length: 730 # bigger than num_values_in
in_channels: 10
n_layers: 2
dim_feedforward: 256
batch_first: true
norm_first: false
lr: 1e-4
layer_norm_eps: 1e-5
transformer_dropout: 0.1
final_dropout: 0.5
conv_strides: [1, 1]
pool_strides: [2, 2]
conv_kernel_sizes: [5, 3]
pool_kernel_sizes: [2, 2]
num_time_features_to_expand: 2
